import "./globals.scss";

export const metadata = {
	title: "Pokédex Next.js 13 Redux",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="main-container">{children}</body>
		</html>
	);
}
